//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_MVC.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/SL_WCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Alumnos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.RecetasAlumnos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Receta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ObjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct {
            get {
                return this.CorrectField;
            }
            set {
                if ((this.CorrectField.Equals(value) != true)) {
                    this.CorrectField = value;
                    this.RaisePropertyChanged("Correct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Ex {
            get {
                return this.ExField;
            }
            set {
                if ((object.ReferenceEquals(this.ExField, value) != true)) {
                    this.ExField = value;
                    this.RaisePropertyChanged("Ex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Objects {
            get {
                return this.ObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsField, value) != true)) {
                    this.ObjectsField = value;
                    this.RaisePropertyChanged("Objects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAll", ReplyAction="http://tempuri.org/IService1/GetAllResponse")]
        PL_MVC.ServiceReference1.Result GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAll", ReplyAction="http://tempuri.org/IService1/GetAllResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReference1.Result> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetByIdEF", ReplyAction="http://tempuri.org/IService1/GetByIdEFResponse")]
        PL_MVC.ServiceReference1.Result GetByIdEF(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetByIdEF", ReplyAction="http://tempuri.org/IService1/GetByIdEFResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReference1.Result> GetByIdEFAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetByMatricula", ReplyAction="http://tempuri.org/IService1/GetByMatriculaResponse")]
        PL_MVC.ServiceReference1.Result GetByMatricula(int matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetByMatricula", ReplyAction="http://tempuri.org/IService1/GetByMatriculaResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReference1.Result> GetByMatriculaAsync(int matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add", ReplyAction="http://tempuri.org/IService1/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Receta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.ServiceReference1.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Alumnos))]
        PL_MVC.ServiceReference1.Result Add(ML.RecetasAlumnos alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Add", ReplyAction="http://tempuri.org/IService1/AddResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReference1.Result> AddAsync(ML.RecetasAlumnos alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update", ReplyAction="http://tempuri.org/IService1/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Alumnos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.RecetasAlumnos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.ServiceReference1.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        PL_MVC.ServiceReference1.Result Update(ML.Receta alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update", ReplyAction="http://tempuri.org/IService1/UpdateResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReference1.Result> UpdateAsync(ML.Receta alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetByIdReceta", ReplyAction="http://tempuri.org/IService1/GetByIdRecetaResponse")]
        PL_MVC.ServiceReference1.Result GetByIdReceta(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetByIdReceta", ReplyAction="http://tempuri.org/IService1/GetByIdRecetaResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceReference1.Result> GetByIdRecetaAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PL_MVC.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PL_MVC.ServiceReference1.IService1>, PL_MVC.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PL_MVC.ServiceReference1.Result GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReference1.Result> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public PL_MVC.ServiceReference1.Result GetByIdEF(int Id) {
            return base.Channel.GetByIdEF(Id);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReference1.Result> GetByIdEFAsync(int Id) {
            return base.Channel.GetByIdEFAsync(Id);
        }
        
        public PL_MVC.ServiceReference1.Result GetByMatricula(int matricula) {
            return base.Channel.GetByMatricula(matricula);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReference1.Result> GetByMatriculaAsync(int matricula) {
            return base.Channel.GetByMatriculaAsync(matricula);
        }
        
        public PL_MVC.ServiceReference1.Result Add(ML.RecetasAlumnos alumno) {
            return base.Channel.Add(alumno);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReference1.Result> AddAsync(ML.RecetasAlumnos alumno) {
            return base.Channel.AddAsync(alumno);
        }
        
        public PL_MVC.ServiceReference1.Result Update(ML.Receta alumno) {
            return base.Channel.Update(alumno);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReference1.Result> UpdateAsync(ML.Receta alumno) {
            return base.Channel.UpdateAsync(alumno);
        }
        
        public PL_MVC.ServiceReference1.Result GetByIdReceta(int Id) {
            return base.Channel.GetByIdReceta(Id);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceReference1.Result> GetByIdRecetaAsync(int Id) {
            return base.Channel.GetByIdRecetaAsync(Id);
        }
    }
}
